### ISSUE TITLE
RLS filters on GR maint 3.8 make errors

### ISSUE THREAD

**Issue by woongjae-yoo** [karel/gr-adapt#10]
hello, when I load the RLS filters on GUI and double click it to change and assign parameters,
console shows many error messages.
my environments are,
gnuradio companion: 3.8 maint
gr-adapt: 3.8 maint

open a GRC editor, one of example GRC(gnuradio basic examples)
and I get a LMS filter block and RLS filter block. for LMS filter block, there were no issues to edit, connect, perform
but RLS made errors right after open block's property window.

below is my console logs, do you have any experience like this?

thank you.

===========================================

woongjaeyoo@woongjaeyoo-desktop:~$ gnuradio-companion
<<< Welcome to GNU Radio Companion 3.8.3.1 >>>

Block paths:
	/usr/share/gnuradio/grc/blocks
	/usr/local/share/gnuradio/grc/blocks

Loading: "/home/woongjaeyoo/examples/analog/noise_power.grc"
>>> Done
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gnuradio/grc/core/blocks/_templates.py", line 59, in _get_template
    return self._template_cache[str(text)]
KeyError: 'adapt.rls_filter_${type}(${first_input}, ${num_taps}, ${delta}, ${lambda}, ${skip}, ${decimation}, ${adapt}, ${reset})'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mako/pyparser.py", line 45, in parse
    return _ast_util.parse(code, "<unknown>", mode)
  File "/usr/lib/python3/dist-packages/mako/_ast_util.py", line 92, in parse
    return compile(expr, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    lambda
         ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gnuradio/grc/core/blocks/_templates.py", line 50, in compile
    template = Template(text, strict_undefined=True)
  File "/usr/lib/python3/dist-packages/mako/template.py", line 331, in __init__
    (code, module) = _compile_text(self, text, filename)
  File "/usr/lib/python3/dist-packages/mako/template.py", line 733, in _compile_text
    source, lexer = _compile(
  File "/usr/lib/python3/dist-packages/mako/template.py", line 712, in _compile
    node = lexer.parse()
  File "/usr/lib/python3/dist-packages/mako/lexer.py", line 262, in parse
    if self.match_expression():
  File "/usr/lib/python3/dist-packages/mako/lexer.py", line 433, in match_expression
    self.append_node(
  File "/usr/lib/python3/dist-packages/mako/lexer.py", line 152, in append_node
    node = nodecls(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mako/parsetree.py", line 204, in __init__
    self.code = ast.PythonCode(text, **self.exception_kwargs)
  File "/usr/lib/python3/dist-packages/mako/ast.py", line 43, in __init__
    expr = pyparser.parse(code.lstrip(), "exec", **exception_kwargs)
  File "/usr/lib/python3/dist-packages/mako/pyparser.py", line 47, in parse
    raise exceptions.SyntaxException(
mako.exceptions.SyntaxException: (SyntaxError) invalid syntax (<unknown>, line 1) ('lambda') at line: 1 char: 65

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gnuradio/grc/core/blocks/_templates.py", line 74, in render
    template = self._get_template(text)
  File "/usr/lib/python3/dist-packages/gnuradio/grc/core/blocks/_templates.py", line 61, in _get_template
    return self.compile(text)
  File "/usr/lib/python3/dist-packages/gnuradio/grc/core/blocks/_templates.py", line 52, in compile
    raise TemplateError(text, *error.args)
gnuradio.grc.core.errors.TemplateError: ('adapt.rls_filter_${type}(${first_input}, ${num_taps}, ${delta}, ${lambda}, ${skip}, ${decimation}, ${adapt}, ${reset})', "(SyntaxError) invalid syntax (<unknown>, line 1) ('lambda') at line: 1 char: 65")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gnuradio/grc/gui/PropsDialog.py", line 210, in update_gui
    self._update_docs_page()
  File "/usr/lib/python3/dist-packages/gnuradio/grc/gui/PropsDialog.py", line 241, in _update_docs_page
    block_constructor = self._block.templates.render('make').rsplit('.', 2)[-1]
  File "/usr/lib/python3/dist-packages/gnuradio/grc/core/blocks/_templates.py", line 77, in render
    raise TemplateError(error, text)
gnuradio.grc.core.errors.TemplateError: (TemplateError('adapt.rls_filter_${type}(${first_input}, ${num_taps}, ${delta}, ${lambda}, ${skip}, ${decimation}, ${adapt}, ${reset})', "(SyntaxError) invalid syntax (<unknown>, line 1) ('lambda') at line: 1 char: 65"), 'adapt.rls_filter_${type}(${first_input}, ${num_taps}, ${delta}, ${lambda}, ${skip}, ${decimation}, ${adapt}, ${reset})')
woongjaeyoo@woongjaeyoo-desktop:~$

**Comment by woongjae-yoo** [comment]
additionally, this is what I figured out between GNUradio branch and gr-adapt branch.
all GNUradio installation is from PPA
GNUradio 3.8 maint + gr-adapt 3.8 maint: fail (LMS is good but for RLS block, as logs above)
GNUradio 3.9 maint + gr-adapt 3.9 maint: fail (filter block constructor error, couldn't build) (https://githubmemory.com/repo/muccc/gr-iridium/issues/54)
GNUradio 3.9 maint + gr-adapt master : success

my goal is on GNUradio 3.8 maint, using gr-adapt with full features.

**Comment by karel** [comment]
Sorry for the late reply. This issue was fixed in 2b86bba11c8155f91970b899abf58336a507b7eb, but hadn't been backported. Now the patch is also applied to `maint-3.8` (c04972f80a00457a66db7f946bd2f2b4ee6f2113).
